Repository Dream-Home-PEABOT/FEE_DreamHome, pull requests merged in 2021-01, with the labels that each got.

#19 Add data structure file
  .eslintcache
  .gitignore
  package-lock.json
  src/_variables.css
  src/data.tsx
  src/images/calculate/Big Shoes - Sitting On Floor-w-bg.png
  src/images/calculate/Big Shoes - Sitting On Floor.png
  src/images/calculate/Charco - Security.png
  src/images/calculate/Fancy Plants - Solo Background.png
  src/images/errors/Big Shoes - Torso.png
  src/images/errors/Charco - Broken.png
  src/images/extras/Big Shoes - Chatting.png
  src/images/extras/Big Shoes - Sitting on Rock.png
  src/images/extras/Fancy Plants - Solo Plant copy.png
  src/images/extras/Fancy Plants - Solo Plant.png
  src/images/home/Big Shoes - Standing Pose.png
  src/images/journey/Big Shoes - Hero.png
  src/images/questions/Big Shoes - Sitting On Floor.png
  src/images/questions/Charco - Location Map.png
  src/images/questions/Fancy Plants - Solo Background.png
  src/images/report/Big Shoes - Dynamic Pose.png
  src/images/report/Big Shoes - Jumping On One leg Pose.png
  src/images/report/Big Shoes - Knealing On Floor.png
  src/images/report/Big Shoes - Sitting On Floor.png
  src/images/report/Big Shoes - Torso.png
  src/images/report/Charco - Good Job.png
  src/images/report/Charco - Inbox.png
  src/images/report/Charco - Location Map.png
  src/images/report/Charco - Mobile Life.png
  src/images/report/Charco - Work at Home.png
  src/images/survey/Big Shoes - Sitting on Rock Blue.png
  src/images/survey/Big Shoes - Sitting on Rock Yellow.png
  src/images/survey/Fancy Plants - Solo Background.png
  src/index.css
  src/index.tsx
Labels: frontend

#24 Om feature display nav bar
  .eslintcache
  package-lock.json
  package.json
  src/apiCalls.tsx
  src/components/App/App.css
  src/components/App/App.tsx
  src/components/Error/Error.tsx
  src/components/NavBar/NavBar.css
  src/components/NavBar/NavBar.tsx
  src/components/Sourvey/Sourvey.tsx
  src/index.tsx
Labels: JSX, RFC, Style

#30 Om feature display journey
  .eslintcache
  public/index.html
  src/_variables.css
  src/components/App/App.tsx
  src/components/Home/Home.css
  src/components/Home/Home.tsx
  src/components/Journey/Journey.css
  src/components/Journey/Journey.tsx
  src/components/NavBar/NavBar.css
  src/components/Sourvey/Sourvey.tsx
Labels: JSX, Style, frontend

#47 Connect question logic
  src/components/App/App.tsx
  src/components/Journey/Journey.tsx
  src/components/NavBar/NavBar.tsx
  src/components/Question/Question.tsx
  src/components/Survey/Survey.tsx
  src/index.tsx
  src/types.tsx
Labels: RFC, data flow

#44 Om feature display report
  src/_variables.css
  src/components/App/App.tsx
  src/components/Report/Report.css
  src/components/Report/Report.tsx
  src/components/Survey/Survey.css
Labels: JSX, RFC, Style, frontend

#52 Om feature display error page
  .eslintcache
  package-lock.json
  package.json
  src/_variables.css
  src/components/App/App.tsx
  src/components/Error/Error.css
  src/components/Error/Error.tsx
  src/components/GenerateReport/GenerateReport.css
  src/components/Home/Home.css
  src/components/Journey/Journey.css
  src/components/NavBar/NavBar.css
  src/components/NavBar/NavBar.tsx
  src/components/NavItem/NavItem.tsx
  src/components/Question/Question.css
  src/components/Report/Report.css
  src/components/Survey/Survey.css
  src/index.css
  src/index.tsx
Labels: JSX, RFC, Style

#55 Question button functionality
  .eslintcache
  src/components/App/App.tsx
  src/components/Question/Question.css
  src/components/Question/Question.tsx
Labels: data flow, enhancement

#62 Report display
  package-lock.json
  package.json
  src/components/App/App.tsx
  src/components/GenerateReport/GenerateReport.tsx
  src/components/NavBar/NavBar.tsx
  src/components/NavItem/NavItem.tsx
  src/components/Question/Question.css
  src/components/Report/Report.css
  src/components/Report/Report.tsx
  src/components/ReportCategory/ReportCategory.tsx
Labels: frontend

#72 Further integration testing
  src/apiCalls.tsx
  src/components/App/App.test.tsx
  src/components/App/App.tsx
  src/components/GenerateReport/GenerateReport.tsx
Labels: testing

#71 Report testing
  .eslintcache
  src/components/Report/Report.tsx
  src/components/ReportCategory/ReportCategory.test.tsx
  src/components/ReportCategory/ReportCategory.tsx
  src/components/Survey/Survey.test.tsx
  src/components/Survey/Survey.tsx
Labels: testing

#75 Unit test
  src/components/Journey/Journey.test.tsx
  src/components/Journey/Journey.tsx
  src/components/NavBar/NavBar.test.tsx
  src/components/NavBar/NavBar.tsx
  src/components/NavItem/NavItem.tsx
  src/components/Question/Question.test.tsx
  src/components/Question/Question.tsx
Labels: frontend

#81 Report category testing
  .eslintcache
  src/components/ReportCategory/ReportCategory.test.tsx
Labels: testing

#90 Om feature loading message
  src/components/Report/Report.css
  src/components/Report/Report.tsx
  src/index.css
Labels: JSX, RFC, Style, frontend

#92 Setup readme
  .eslintcache
  .travis.yml
  README.md
  package-lock.json
  src/apiCalls.tsx
  src/components/Error/Error.test.tsx
  src/jest/react-spring-mock.js
Labels: documentation

#94 Generate report testing
  src/components/GenerateReport/GernerateReport.test.tsx
Labels: testing

#129 Firebase Authenticaiton
  .firebaserc
  firebase.json
  package.json
  public/index.html
  src/components/App/App.tsx
  src/components/Login/Login.css
  src/components/Login/Login.test.tsx
  src/components/Login/Login.tsx
  src/components/NavBar/NavBar.tsx
  src/helpers/firebase.tsx
  src/index.tsx
Labels: Style, data flow, frontend

#140 Display report v2
  src/components/App/App.tsx
  src/components/GenerateReport/GenerateReport.tsx
  src/components/Profile/Profile.tsx
  src/components/Question/Question.css
  src/components/Question/Question.tsx
  src/components/Report/Report.css
  src/components/ReportCategory/ReportCategory.tsx
  src/components/ReportSecThree/ReportSecThree.css
  src/components/ReportSecThree/ReportSecThree.tsx
  src/components/ReportSecTwo/ReportSecTwo.css
  src/components/ReportSecTwo/ReportSecTwo.tsx
  src/helpers/apiCalls.tsx
  src/helpers/types.tsx
Labels: bug, frontend, help wanted

#144 Link uid to report
  src/components/App/App.tsx
  src/components/App/data.tsx
  src/components/GenerateReport/GenerateReport.tsx
  src/components/Home/Home.tsx
  src/components/NavBar/NavBar.tsx
  src/components/Profile/Profile.tsx
  src/components/Report/Report.css
  src/components/Report/Report.tsx
  src/components/ReportCategory/ReportCategory.tsx
  src/components/ReportSecOne/ReportSecOne.tsx
  src/helpers/apiCalls.tsx
  src/helpers/types.tsx
  src/index.css
Labels: frontend

#145 Edit profile
  src/components/App/App.tsx
  src/components/Error/Error.tsx
  src/components/GenerateReport/GenerateReport.tsx
  src/components/Journey/Journey.css
  src/components/NavBar/NavBar.tsx
  src/components/Profile/Profile.css
  src/components/Profile/Profile.tsx
  src/components/ReportSecOne/ReportSecOne.tsx
  src/helpers/apiCalls.tsx
Labels: JSX, RFC, Style, frontend

#147 Display loader
  src/components/App/App.tsx
  src/components/GenerateReport/GenerateReport.tsx
  src/components/Journey/Journey.tsx
  src/components/Login/Login.css
  src/components/Login/Login.tsx
  src/components/Profile/Profile.css
  src/components/Report/Report.css
  src/components/ReportCategory/ReportCategory.tsx
  src/components/ReportSecOne/ReportSecOne.tsx
  src/components/Survey/Survey.tsx
Labels: JSX, RFC, Style

#151 Fix report typos
  src/components/Report/Report.css
  src/components/ReportCategory/ReportCategory.tsx
  src/components/ReportSecOne/ReportSecOne.tsx
Labels: bug
